CREATE TABLE DEPOSITOR (
    account_no NUMBER(5) PRIMARY KEY,
    name VARCHAR2(20),
    amt NUMBER(10)
);

CREATE TABLE BORROWER (
    loan_no NUMBER(5) PRIMARY KEY,
    name VARCHAR2(20),
    amt NUMBER(10)
);
DESC DEPOSITOR 
INSERT INTO DEPOSITOR VALUES (101, 'Suman', 50000);
INSERT INTO DEPOSITOR VALUES (102, 'Amit', 30000);
INSERT INTO DEPOSITOR VALUES (103, 'Riju', 40000);

INSERT INTO BORROWER VALUES (201, 'Suman', 30000);
INSERT INTO BORROWER VALUES (202, 'Nayan', 15000);
INSERT INTO BORROWER VALUES (203, 'Riju', 25000);

SELECT * FROM DEPOSITOR;
SELECT * FROM BORROWER;

SELECT name FROM DEPOSITOR INTERSECT SELECT name FROM BORROWER;
SELECT name FROM DEPOSITOR MINUS SELECT name FROM BORROWER;
SELECT name FROM DEPOSITOR UNION SELECT name FROM BORROWER;
SELECT name FROM DEPOSITOR UNION ALL SELECT name FROM BORROWER;






